plugins {
    id 'io.freefair.lombok' version '8.13.1'
    id 'org.jreleaser' version '1.22.0'
    id 'maven-publish'
    id 'signing'
    id 'java-library'
    id 'idea'
}
apply from: rootProject.file("publishing.gradle")

dependencies {
    api project(':system-dict-core')
    api project(':system-dict-spring-boot')
    compileOnly('org.slf4j:slf4j-api:2.0.17')
    compileOnly 'org.jspecify:jspecify:1.0.0'
    compileOnly 'com.fasterxml.jackson.core:jackson-databind:2.13.5'
    compileOnly 'org.springframework:spring-web:5.3.31'
    compileOnly 'org.springframework:spring-context:5.3.31'
    compileOnly 'org.springframework.data:spring-data-redis:2.7.18'
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure:2.7.18'
}

java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
