plugins {
    // id 'org.springframework.boot' version '4.0.1'
    // id 'io.spring.dependency-management' version '1.1.7'
    // id "io.freefair.lombok" version '8.13.1'
    id 'org.jreleaser' version '1.22.0'
    // id 'maven-publish'
    // id 'signing'
    // id 'java-library'
    id 'application'
    id 'idea'
}

group = 'com.houkunlin'
version = '2.0.3'
description = """
系统数据字典自动翻译成字典文本。可集合系统数据库中存储的用户数据字典，也可使用枚举做系统数据字典，主要用在返回数据给前端时自动把字典值翻译成字典文本信息；
SpringBoot 2.7.18 和 Java 8 请使用 1.5.8 版本.
SpringBoot 3.x 请使用 1.6.x 版本.
SpringBoot 4.x 请使用 1.7.x 或 2.x 版本.
SpringBoot 2.7.18 AND Java 8 Please use 1.5.8 version.
SpringBoot 3.x Please use 1.6.x version.
SpringBoot 4.x Please use 1.7.x or 2.x version.
The system data dictionary is automatically translated into dictionary text.
The user data dictionary stored in the system database can be aggregated, and the enumeration can also be used as the system data dictionary.
It is mainly used to automatically translate dictionary values into dictionary text information when returning data to the front end.
"""

allprojects {
    repositories {
        mavenCentral()
        maven {
            url = "https://repo1.maven.org/maven2"
        }
        mavenCentral()
        maven {
            url = "https://repo.spring.io/artifactory/libs-milestone-local/"
        }
        maven {
            url = "https://repo.spring.io/artifactory/libs-release-local/"
        }
    }

    def isSnapshot = findProperty("snapshot") != null || version.endsWith('SNAPSHOT')

    if (isSnapshot && !version.endsWith('SNAPSHOT')) {
        version += '-BUILD-SNAPSHOT'
    }

    idea {
        module {
            downloadJavadoc = true
            downloadSources = true
        }
    }

    javadoc {
        enabled = true
        options.encoding = "UTF-8"
        options.addStringOption('Xdoclint:none', '-quiet')
    }

    compileJava {
        options.encoding = "UTF-8"
    }

    test {
        useJUnitPlatform()
    }

}
