plugins {
    id 'io.freefair.lombok' version '8.13.1'
    id 'org.jreleaser' version '1.22.0'
    id 'maven-publish'
    id 'signing'
    id 'java-library'
    id 'idea'
    id 'java-test-fixtures'
}
apply from: rootProject.file("publishing.gradle")

dependencies {
    api project(':system-dict-core')
    compileOnly 'org.slf4j:slf4j-api:2.0.17'
    compileOnly 'com.github.ben-manes.caffeine:caffeine:2.9.3'
    compileOnly 'com.google.guava:guava:33.5.0-jre'
    compileOnly 'org.jspecify:jspecify:1.0.0'
    compileOnly 'io.swagger.core.v3:swagger-annotations:2.2.41'
    compileOnly 'com.fasterxml.jackson.core:jackson-annotations:2.13.5'
    compileOnly 'org.springframework:spring-webmvc:5.3.31'
    compileOnly 'org.springframework.boot:spring-boot:2.7.18'
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure:2.7.18'
    compileOnly 'org.springframework.boot:spring-boot-actuator:2.7.18'
    compileOnly 'org.springframework.boot:spring-boot-starter-amqp:2.7.18'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-redis:2.7.18'

    testFixturesCompileOnly 'org.springframework:spring-web:5.3.31'
    testFixturesCompileOnly 'org.springframework.boot:spring-boot-autoconfigure:2.7.18'
    testFixturesCompileOnly 'com.fasterxml.jackson.core:jackson-annotations:2.13.5'
    testFixturesCompileOnly 'com.github.ben-manes.caffeine:caffeine:2.9.3'
    testFixturesCompileOnly('org.slf4j:slf4j-api:2.0.17')
    testFixturesCompileOnly('org.junit.jupiter:junit-jupiter-api:5.10.2')
    testFixturesApi 'org.skyscreamer:jsonassert:1.5.3'
}
java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
compileJava {
    options.compilerArgs += ['-parameters']
}
