plugins {
    id 'io.freefair.lombok' version '8.13.1'
    id 'org.jreleaser' version '1.22.0'
    id 'maven-publish'
    id 'signing'
    id 'java-library'
    id 'idea'
}
apply from: rootProject.file("publishing.gradle")

dependencies {
    compileOnly 'com.fasterxml.jackson.core:jackson-annotations:2.20'
    compileOnly 'io.swagger.core.v3:swagger-annotations:2.2.41'
    compileOnly 'org.slf4j:slf4j-api:2.0.17'
    compileOnly 'com.github.ben-manes.caffeine:caffeine:2.9.3'
    compileOnly 'org.springframework:spring-core:5.3.31'
    compileOnly 'org.springframework.boot:spring-boot:2.7.18'
}

java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
