plugins {
    id 'io.freefair.lombok' version '8.13.1'
    id 'org.jreleaser' version '1.22.0'
    id 'maven-publish'
    id 'signing'
    id 'java-library'
    id 'idea'
}
apply from: rootProject.file("publishing.gradle")

dependencies {
    api project(':system-dict-core')
    api project(':system-dict-spring-boot')
    compileOnly('org.slf4j:slf4j-api:2.0.17')
    compileOnly 'org.jspecify:jspecify:1.0.0'
    compileOnly 'tools.jackson.core:jackson-databind:3.0.3'
    compileOnly 'org.springframework:spring-context:7.0.2'
    compileOnly 'org.springframework.data:spring-data-redis:4.0.1'
    compileOnly 'org.springframework.boot:spring-boot-autoconfigure:4.0.1'
    compileOnly 'org.springframework.boot:spring-boot-jackson:4.0.1'
}

java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
