plugins {
    id 'org.springframework.boot' version '3.0.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.freefair.lombok' version '8.13.1'
    id 'org.jreleaser' version '1.22.0'
    id 'maven-publish'
    id 'signing'
    id 'java-library'
    id 'idea'
}
apply from: rootProject.file("publishing.gradle")

dependencies {
    api project(':system-dict-core')
    api project(':system-dict-spring-boot')
    api project(':system-dict-spring-boot-jackson2')
    compileOnly 'org.springframework.boot:spring-boot-starter-validation'
    compileOnly 'io.swagger.core.v3:swagger-annotations:2.2.41'

    api 'com.github.ben-manes.caffeine:caffeine'
    api 'com.google.guava:guava:33.5.0-jre'

    testImplementation 'org.springframework.boot:spring-boot-starter-actuator'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-redis'
    testImplementation 'io.swagger.core.v3:swagger-annotations:2.2.41'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation testFixtures(project(':system-dict-spring-boot'))
}
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}
bootJar {
    enabled = false
}
java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
jar {
    enabled = true
    setArchiveClassifier("")
}

